# Generated by Django 5.0.7 on 2024-07-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='oid',
            field=models.CharField(default='1', max_length=64, verbose_name='订单号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(default='1;', max_length=32, verbose_name='商品名称'),
            preserve_default=False,
        ),
    ]
