# Generated by Django 5.0.7 on 2024-07-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_order_oid_order_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('img', models.CharField(max_length=128, verbose_name='头像')),
            ],
        ),
    ]
